# This workflow will run tests using node when code is pushed to main.

name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: sudo apt install -y socat

      - run: npm ci
      - run: npm test
